/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Alberto
 */
public class Graphics extends javax.swing.JFrame {

    /**
     * Creates new form Graphics
     */
    public Graphics() {
        initComponents();
        this.setSize(1000, 750);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field_weather = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        field_route = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        field_locality = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        field_postalcode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        field_country = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        field_address = new javax.swing.JTextField();
        field_temperature = new javax.swing.JTextField();
        field_humidity = new javax.swing.JTextField();
        field_pressure = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(field_weather);
        field_weather.setBounds(390, 130, 200, 40);

        jLabel1.setText("Insert address");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 110, 200, 20);

        jLabel2.setText("Insert route");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 180, 200, 20);
        getContentPane().add(field_route);
        field_route.setBounds(100, 200, 200, 40);

        jLabel3.setText("Insert locality");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 250, 200, 20);
        getContentPane().add(field_locality);
        field_locality.setBounds(100, 270, 200, 40);

        jLabel4.setText("Insert postal code");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 320, 200, 20);
        getContentPane().add(field_postalcode);
        field_postalcode.setBounds(100, 340, 200, 40);

        jLabel5.setText("Insert country");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 390, 200, 20);
        getContentPane().add(field_country);
        field_country.setBounds(100, 410, 200, 40);

        jButton1.setText("Find");
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 470, 90, 25);
        getContentPane().add(field_address);
        field_address.setBounds(100, 130, 200, 40);
        getContentPane().add(field_temperature);
        field_temperature.setBounds(390, 200, 200, 40);
        getContentPane().add(field_humidity);
        field_humidity.setBounds(390, 270, 200, 40);
        getContentPane().add(field_pressure);
        field_pressure.setBounds(390, 340, 200, 40);

        jLabel6.setText("Weather");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 110, 200, 20);

        jLabel7.setText("Temperature");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(390, 180, 200, 20);

        jLabel8.setText("Humidity");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(390, 250, 200, 20);

        jLabel9.setText("Pressure");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(390, 320, 200, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graphics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field_address;
    private javax.swing.JTextField field_country;
    private javax.swing.JTextField field_humidity;
    private javax.swing.JTextField field_locality;
    private javax.swing.JTextField field_postalcode;
    private javax.swing.JTextField field_pressure;
    private javax.swing.JTextField field_route;
    private javax.swing.JTextField field_temperature;
    private javax.swing.JTextField field_weather;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
